name: Merge Queue Tasks

on:
  merge_group:
  workflow_dispatch:

jobs:
  invoke-build-rust:
    name: Build Rust
    uses: ./.github/workflows/build-rust.yml

  invoke-build-java:
    name: Build Java
    uses: ./.github/workflows/build-java.yml

  invoke-tests-unit:
    name: Unit Tests
    needs: [invoke-build-rust, invoke-build-java]
    uses: ./.github/workflows/test-unit.yml

  invoke-tests-adapter:
    name: Adapter Tests
    needs: [invoke-build-rust]
    uses: ./.github/workflows/test-adapters.yml
    secrets: inherit

  invoke-build-docker:
    name: Build Docker
    needs: [invoke-build-rust, invoke-build-java]
    uses: ./.github/workflows/build-docker.yml

  invoke-tests-integration:
    name: Integration Tests
    needs: [invoke-build-docker]
    uses: ./.github/workflows/test-integration.yml

  invoke-tests-java:
    name: Java Tests
    needs: [invoke-build-java]
    uses: ./.github/workflows/test-java.yml

  main:
    name: Merge Queue Tasks
    runs-on: ubuntu-latest
    needs:
      - invoke-build-rust
      - invoke-build-java
      - invoke-tests-unit
      - invoke-tests-adapter
      - invoke-build-docker
      - invoke-tests-integration
      - invoke-tests-java
    steps:
      - name: Finalize Workflow
        run: echo "All tasks completed successfully!"
